parameters:
#    acme_store.example.class: Acme\StoreBundle\Example
    acme_store.mongo_persister.class: Acme\StoreBundle\Services\MongoPersister

services:

    acme_store.mongo_persister:
         class: %acme_store.mongo_persister.class%
         calls:
            - [setMongoManager, [ @doctrine_mongodb ] ]