acme_store_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeTrainingBundle:Default:index }

product_create:
    pattern: /product/create
    defaults: {_controller: AcmeTrainingBundle:Default:create }

product_load:
    pattern: /product/load-by-name/{name}
    defaults: {_controller: AcmeTrainingBundle:Default:loadByName }

product_demo:
    pattern: /product/load-by-id/{id}
    defaults: {_controller: AcmeTrainingBundle:Default:loadById }