parameters:
    acme_training.persister.class: Acme\TrainingBundle\Services\Persister
    acme_training.customer_role_handler.class: Acme\TrainingBundle\Services\CustomerRoleHandler

services:

    acme_training.mongo_persister:
         class: %acme_training.persister.class%
         calls:
            - [setObjectManager, [ @doctrine_mongodb.odm.document_manager ] ]

    acme_training.mysql_persister:
         class: %acme_training.persister.class%
         calls:
            - [setObjectManager, [ @doctrine.orm.entity_manager ] ]

    acme_training.customer_role_handler:
         class: %acme_training.customer_role_handler.class%
         calls:
            - [setSerializer, [@jms_serializer]]