parameters:
    acme_training.persister.class: Acme\TrainingBundle\Services\Persister

services:

    acme_training.mongo_persister:
         class: %acme_training.persister.class%
         calls:
            - [setObjectManager, [ @doctrine_mongodb.odm.document_manager ] ]

    acme_training.mysql_persister:
         class: %acme_training.persister.class%
         calls:
            - [setObjectManager, [ @doctrine.orm.entity_manager ] ]